language: node_js

node_js:
  - "node"

install: npm install

script: 
  - npm run lint
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  repo: music-markdown/music-markdown.github.io
  target_branch: master
  local-dir: build
  on:
    branch: master
