language: node_js

node_js:
  - "11.10"   # Remove when create-react-app updates jest to 24
#  - "node"   # Uncomment when create-react-app updates to jest 24

install: npm install

script:
  - npm test
  - npm run lint
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  repo: music-markdown/music-markdown.github.io
  target_branch: master
  local-dir: build
  on:
    branch: master
