export const TRANSPOSE = 'TRANSPOSE';
export const UPDATE_COLUMN_COUNT = 'UPDATE_COLUMN_COUNT';
export const UPDATE_FONT_SIZE = 'UPDATE_FONT_SIZE';
export const UPDATE_YOUTUBE_ID = 'UPDATE_YOUTUBE_ID';
export const SET_DARK_THEME = 'SET_DARK_THEME';
